apiVersion: v1
kind: Pod
metadata:
  name: prod-go-server
  labels:
    app: api
spec:
  containers:
    - name: go-server
      image: go-server
      imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
    - port: 3000
      name: go-server
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: api
