apiVersion: v1
kind: Pod
metadata:
  name: adapter-example
  namespace: default
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
    - name: adapter
      image: oliver006/redis_exporter
      ports:
        - containerPort: 9121
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      name: "redis-port"
      targetPort: 6379
    - port: 9121
      name: "redis-exporter-port"
      targetPort: 9121
  selector:
    app: redis
