apiVersion: v1
kind: Pod
metadata:
  name: adapter-example
  namespace: default
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
    - name: fluentd
      image: fluentd
      imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      name: "redis-port"
      targetPort: 6379
  selector:
    app: redis
