apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-shard
spec:
  selector:
    matchLabels:
      app: go-server
  serviceName: "web"
  replicas: 3
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
        - name: web-shard
          image: go-server
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: go-server
  clusterIP: None
  # ports:
  #   - protocol: TCP
  #     port: 80
  #     targetPort: 8080
