apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: go-server-rs
  labels:
    app: api-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: go-server
          image: go-server
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: app-lb
spec:
  ports:
    - port: 3000
      name: go-server
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: api
